---
- name: Enable faster reconnect via Bluetooth
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/bluetooth/main.conf"
    line: "FastConnectable = {{ fast_connectable|bool|string|lower }}"
    regexp: '^.*FastConnectable\s*=\s*.*$'
    mode: '0644'
    create: true
    backup: true
