---
- name: Setup the kernel module
  include_tasks:
    file: kernel.yml
    apply:
      tags:
      - kernel
      - module
  tags:
  - always

- name: Tune Bluetooth settings
  when: tune_bluetooth
  include_tasks:
    file: bluetooth.yml
    apply:
      tags:
      - bluetooth
  tags:
  - always
