---
- name: Setup the kernel module
  when: ansible_system|lower == 'linux'
  include_tasks:
    file: kernel.yml
    apply:
      tags:
        - kernel
        - module
  tags:
    - always

- name: Tune Bluetooth settings
  when:
    - ansible_system|lower == 'linux'
    - tune_bluetooth
  include_tasks:
    file: bluetooth.yml
    apply:
      tags:
        - bluetooth
  tags:
    - always
